spring:
  application:
    name: analise-cidades
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  redis:
    host: localhost
    port: 6379
    timeout: 2000

apis:
  openweather:
    name: openweather-client
    key: b3d98d474967e5c7e8ef2fb9792ce697
    url: https://api.openweathermap.org/data/2.5
  ibge:
    url: https://servicodados.ibge.gov.br/api/v1/localidades

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      ibge-client:
        connectTimeout: 3000
        readTimeout: 8000
      openweather-client:
        connectTimeout: 4000
        readTimeout: 8000

  logging:
    level:
      root: INFO
      com.exemplo.api: DEBUG
      feign: DEBUG